language: csharp
mono: latest
dotnet: 2.1.300
env: VER=$(if [[ "${TRAVIS_TAG:0:1}" == "v" ]]; then echo ${TRAVIS_TAG:1}.${TRAVIS_BUILD_NUMBER}-beta; else echo 0.0.1.${TRAVIS_BUILD_NUMBER}-alpha; fi;)
install:
  - dotnet restore build.proj
script:
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5-api/
  - dotnet fake run build.fsx -- build test -ll Diag
deploy:
  - provider: script
    script: dotnet fake run build.fsx -- pack push -ll Diag
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG:0:1} = v"
